### ISSUE TITLE
Support scanning multiple directories

### ISSUE THREAD

**Issue by GeofferyMedved** [PavanMudigonda/lines-of-code-reporter#5]
Allow users to pass a comma separated list (or other syntax) of multiple directories for line counting.

**Comment by PavanMudigondaTR** [comment]
The below changes are being added part of this PR.
- [x] Support Multiple Directories. Comma Separated
- [x] Include Languages Input. Comma Separated
- [x] Exclude Directory Input. Comma Separated
- [x] Exclude Languages Input. Comma Separated
- [x] Include File Extension Input. Comma Separated
- [x] Exclude File Extension Input. Comma Seperated
- [x] Update Check to Success from Neutral
- [x] Update Check to show Lines of Code
- [x] Updated Documentation README.md

**Comment by PavanMudigondaTR** [comment]
@GeofferyMedved  This is done. Please use v1.5. Also ReadMe is updated with full documentation.
